# Day 17

### Numpy

In [1]:
import numpy as np

In [2]:
x = np.zeros(5)

In [3]:
x

array([0., 0., 0., 0., 0.])

In [4]:
y = np.ones(5)

In [5]:
y

array([1., 1., 1., 1., 1.])

In [6]:
z = [1,22, 42, 53, 433]
np.array(z)

array([  1,  22,  42,  53, 433])

In [7]:
np.ones(shape=(2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
x.dtype

dtype('float64')

In [15]:
vals = [1,2,3,4,5,6,7,8,9]
x = np.array(vals)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x = x.reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
np.eye(5, dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [52]:
np.random.randint(2, 10, 5)

array([5, 4, 8, 6, 5])

In [55]:
np.linspace(1,10, num=20)  #<- generating 20 intervals in range of 1 to 10

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [57]:
np.linspace(1, 10, num=10, endpoint=False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [58]:
np.linspace(1, 10, num=10, retstep=True) # <= Returns sample and interval size

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

In [61]:
np.logspace(1, 10, num=15)

array([1.00000000e+01, 4.39397056e+01, 1.93069773e+02, 8.48342898e+02,
       3.72759372e+03, 1.63789371e+04, 7.19685673e+04, 3.16227766e+05,
       1.38949549e+06, 6.10540230e+06, 2.68269580e+07, 1.17876863e+08,
       5.17947468e+08, 2.27584593e+09, 1.00000000e+10])

In [63]:
y

array([1., 1., 1., 1., 1.])

In [65]:
%timeit sum(y)

1.66 µs ± 29.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [66]:
%timeit np.sum(y)

4.1 µs ± 308 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [70]:
test_list = np.random.randint(1, 100, 999999)

In [71]:
%timeit sum(test_list)

87.5 ms ± 2.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [72]:
%timeit np.sum(test_list)

608 µs ± 43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [74]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
x * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [77]:
x ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [78]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [80]:
np.log(x)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [82]:
x**2 + 2*x + 1

array([[  4,   9,  16],
       [ 25,  36,  49],
       [ 64,  81, 100]])