# Day 18

### Numpy Continued...

In [20]:
import numpy as np

In [1]:
#CW : A function for matrix multiplication

In [109]:
def mat_mul(mat1, mat2):
    if len(mat1[0]) == len(mat2):
#         print("Mat Mul Possible!")
        matrix1, matrix2 = (mat1, mat2) if len(mat1[0]) < len(mat2) else (mat2, mat1)
        new_matrix = []
        
        for i in range(len(matrix1)):
            row = []
            for j in range(len(matrix2)):
                element = 0
                for k in range(len(matrix2)):
                    element += matrix1[i][k] * matrix2[k][j]
                row.append(element)
            
            new_matrix.append(row)
        return new_matrix
    else:
        print("Dimensions of matrices not appropriate to multiply!")

In [110]:
x = [[1,2,3], [2,4,5]]
y = [[1, 2], [3,4], [4,6]]
mat_mul(x, y)

[[5, 10], [11, 22], [16, 32]]

In [64]:
np.matmul(x, y)

array([[19, 28],
       [34, 50]])

In [35]:
matrix1 = np.random.randint(1, 200, 25).reshape(5,5)
matrix2 = np.random.randint(1, 200, 25).reshape(5,5)

In [36]:
%timeit mat_mul(matrix1, matrix2)

88.6 µs ± 14.8 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
%timeit np.matmul(matrix1, matrix2)

The slowest run took 8.47 times longer than the fastest. This could mean that an intermediate result is being cached.
3.27 µs ± 3.86 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [58]:
x = np.array([1,2,3,4,5,6,7,8,9])
x = x.reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
x.ravel() # <- Flatten the ndarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
x.reshape((-1, 1))  #<- '-1' for indefinite dimension

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

#### Sliscing in NP Arrays

In [66]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
c = z[0:1:1, 0:1:2]
c

array([[1]])

In [73]:
c[0][0] = 500

In [74]:
z    # <- The changed valued in c is also reflected in orignal z array
# Use .copy() to prevent this!

array([[500,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

#### Broadcasting in NP arrays

In [92]:
a = np.array([1,2,3,4,5,6]).reshape(3,2)
b = np.array([10])

In [93]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
b

array([10])

In [97]:
a + b  # <- Here the array b is streched upto the dimension of narray a before the operations

array([[11, 12],
       [13, 14],
       [15, 16]])

In [99]:
xx = np.random.randint(1, 10, 5).reshape((-1, 1))
xx

array([[7],
       [4],
       [7],
       [6],
       [6]])

In [107]:
yy = np.ones((5, 5), dtype='int')
yy

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [108]:
zz = yy + xx
zz

array([[8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5],
       [8, 8, 8, 8, 8],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])